#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HalmaAndroid.Resource", IsApplication=true)]

namespace HalmaAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int playerTypes = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int gradient0 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int numberOfPlayers = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int playerType0 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int playerType0text = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int playerType1 = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int playerType1text = 2131099651;
			
			// aapt resource value: 0x7f060006
			public const int playerType2 = 2131099654;
			
			// aapt resource value: 0x7f060005
			public const int playerType2text = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int playerType3 = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int playerType3text = 2131099655;
			
			// aapt resource value: 0x7f06000a
			public const int playerType4 = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int playerType4text = 2131099657;
			
			// aapt resource value: 0x7f06000b
			public const int startGameButton = 2131099659;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Menu = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int menuActivityLabel = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int numberOfPlayers = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int player0 = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int player1 = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int player2 = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int player3 = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int player4 = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int startGame = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
